version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npx audit-ci --low --report-type full

      - run: npm ci

      - run: npm run standardize:ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run pretest
      - run: npm run test:nyc

      - store_artifacts: # upload test coverage as artifact
          path: ./coverage
      - store_test_results:
          path: ./coverage